version: '3.5'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
    networks:
      - kafka-cluster-network

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure:3
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_CLIENT_USER=user
      - KAFKA_CLIENT_PASSWORD=password
      - KAFKA_CERTIFICATE_PASSWORD=certificatePassword123

    volumes:
      - './ssl/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './ssl/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster-network


networks:
    kafka-cluster-network:
        driver: bridge
        name: kafka-cluster-network